export let IRFconfig = {
  FatSack: true,
  Leaper: true,
  Monstro: true,
  Mom: true,
  Peep: true,
  blastocyst: true,
  Daddy: true,
  DadAlt: true,
  MomHand: true,
  MegaFatty: true,
  ALeach: true,
  Beelzeblub: true,
  Singe: true,
  Adversary: true,
  Delirium: true,
  MegaSatan: true,
  UltraGreed:true,
  GreedCoin:true,
  Mother: false,
  //Fiend Folio
  Slammer: true,
  Poobottle: true,
  Diplet: true,
  Battie: true,
  Monsoon: true,
  Peeping: true,
  Tsar: true,
  Dusk: true,
  RockFall: true,
  AllProjectile: false,
  //Revelations
  FatSnow: true,
  Chuck: true,
  Glasstro: true,
  Aragnid: true,
  Catastroph: true,
  //Splashy
  Splashy: true,
  RogHorn: true,
  //Revelations
}